### ISSUE TITLE
[BUG] docker container does not start with latest image

### ISSUE THREAD

**Issue by mstilkerich** [Elrondo46/davical-docker-standalone#2]
* **I'm submitting a ...**
  - [X] bug report

* **Do you want to request a *feature* or report a *bug*?**

Report a bug

* **What is the current behavior?**

The latest pushed tag of the docker image does not start anymore. I guess the problem is that the shebang in docker-entrypoint.sh is now on line 2 preceded by an empty line. Removing the empty line makes it start again.

```
Service container davical failed.
  /usr/bin/docker logs --details fb6b8cd40b0c504c0079032095f01a3945fe62bb26ea3ccebb8979378c7aab3a
   exec /sbin/docker-entrypoint.sh: exec format error
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Just try to start a container, it won't work.

**Comment by Elrondo46** [comment]
I think it's now fixed. Please confirm and thanks for reporting.
