### ISSUE TITLE
[BUG] role "davical_dba" is not permitted to log in

### ISSUE THREAD

**Issue by jejbq** [Elrondo46/davical-docker-standalone#3]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

Multiple errors related to davical_dba during startup
role "davical_dba" is not permitted to log in

The container is unable to initialize or update the davical database when the davical_dba user is used. 
but works with the postgres user. Basically, all lines with davical_dba from docker-entrypoint.sh failed.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

You need to add the following lines to docker-entrypoint.sh to make it work

```
    PGPASSWORD="$PGSQL_ROOT_PASS" /usr/bin/psql -qX -U postgres -h "$DBHOST" -c 'ALTER ROLE davical_dba LOGIN;'
    PGPASSWORD="$PGSQL_ROOT_PASS" /usr/bin/psql -qX -U postgres -h "$DBHOST" -c 'ALTER ROLE davical_app LOGIN;'
```

* **What is the expected behavior?**

Initialize or update the davical database properly.

* **What is the motivation / use case for changing the behavior?**

N/A

* **Please tell us about your environment:**
  
  - Version: latest (81-1.1.12)

**Comment by Elrondo46** [comment]
Bug confirmed, post it as a pull request. I will accept it. Why there is this bug, I don't know. Old releases worked like a charm

**Comment by Elrondo46** [comment]
Ok all fixed, you have the origin of the issue and credits for solve it. Thanks

**Comment by jejbq** [comment]
In fact, you miss LOGIN next to CREATE ROLE and the default attribute for new role is NOLOGIN

So if you want to fix existing docker volumes:
```
if [[ -z "$INITIALIZED_DB" ]]; then
...
    PGPASSWORD="$PGSQL_ROOT_PASS" /usr/bin/psql -qX -U postgres -h "$DBHOST" -c 'CREATE ROLE davical_dba LOGIN;'
    PGPASSWORD="$PGSQL_ROOT_PASS" /usr/bin/psql -qX -U postgres -h "$DBHOST" -c 'CREATE ROLE davical_app LOGIN;'
...
else
...
    PGPASSWORD=$PGSQL_ROOT_PASS /usr/bin/psql -qX -U postgres -h $DBHOST -c 'ALTER USER davical_dba WITH LOGIN;'
    PGPASSWORD=$PGSQL_ROOT_PASS /usr/bin/psql -qX -U postgres -h $DBHOST -c 'ALTER USER davical_app WITH LOGIN;'
...
fi
```

https://www.postgresql.org/docs/current/sql-createrole.html
```    
If not specified, NOLOGIN is the default, except when CREATE ROLE is invoked through its alternative spelling [CREATE USER](https://www.postgresql.org/docs/current/sql-createuser.html).
```

**Comment by Elrondo46** [comment]
Thanks for your help

**Comment by Elrondo46** [comment]
Can you test if davical image is now compatible with PGSQL15 and newer ?

**Comment by jejbq** [comment]
I am using the latest postgres image (PostgreSQL 15) as your docker-compose.yml
